name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3']
        checks: ['race', 'msan', 'asan']
        exclude:
          - php-versions: 8.3
            checks: msan
          - php-versions: 8.3
            checks: asan
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: |
            go.sum 
            caddy/go.sum
      -
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-file: development
          extensions: ${{ matrix.checks != 'race' && 'none' || '' }}
          coverage: none
          tools: none
        env:
          phpts: ts
      -
        name: Remove remaining extensions
        if: matrix.checks != 'race'
        run: rm -Rf /usr/lib/php/*-zts/*.so
      -
        name: Set CGO flags
        run: |
          echo "CGO_CFLAGS=$(php-config --includes)" >> "$GITHUB_ENV"
          echo "CC=${{ matrix.checks == 'race' && 'gcc' || 'clang' }}" >> "$GITHUB_ENV"
      -
        name: Build
        run: go build
        env:
          GOEXPERIMENT: cgocheck2
      -
        name: Run library tests
        run: go test -${{ matrix.checks }} -v ./...
      -
        name: Run Caddy module tests
        working-directory: caddy/
        run: go test -${{ matrix.checks }} -v ./...
